# Generated by Django 4.1.5 on 2023-01-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receiver_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.receiver_info'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.sender_info'),
        ),
    ]
