# Generated by Django 4.1.5 on 2023-01-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_driver',
            name='deliveries',
            field=models.ManyToManyField(to='delivery.delivery'),
        ),
    ]
